# Generated by Django 2.1.3 on 2018-12-04 05:33

import angel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=30)),
                ('registered_id', models.CharField(max_length=30)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to=angel.models._hashed_name)),
                ('contribution', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(upload_to=angel.models._hashed_name)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='honors',
            field=models.ManyToManyField(to='angel.Honor'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='led_group', to='angel.Angel'),
        ),
        migrations.AddField(
            model_name='angel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angels', to='angel.Group'),
        ),
        migrations.AddField(
            model_name='angel',
            name='honors',
            field=models.ManyToManyField(to='angel.Honor'),
        ),
    ]
