# Generated by Django 2.1.3 on 2018-11-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('registered_name', models.CharField(max_length=30)),
                ('registered_id', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
