# Generated by Django 2.1.3 on 2018-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angel',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
