# Generated by Django 2.1.3 on 2018-11-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='angel',
            name='identifier',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
