# Generated by Django 2.1.3 on 2018-12-01 18:39

import angel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0002_auto_20181201_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angel',
            name='avatar',
            field=models.ImageField(upload_to=angel.models._hashed_name),
        ),
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(upload_to=angel.models._hashed_name),
        ),
    ]
