# Generated by Django 2.1.3 on 2018-11-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('angel', '0002_angel_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('cost', models.FloatField()),
                ('point', models.IntegerField()),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_tasks', to='angel.Angel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_task', to='angel.Angel')),
            ],
        ),
    ]
